theme: jekyll-theme-minimal

title: OSM-Sandbox's Helm chart repository
description: >
  This is the human-friendly view of the osm-sandbox's Helm chart repository
  where Helm charts developed elsewhere are published. The command line tool
  <code>helm</code> interacts with <a href="index.yaml">index.yaml</a>.

stableCharts:
  - osm-sandbox